test

diff --git a/.github/workflows/pull-request.yml b/.github/workflows/pull-request.yml
--- a/.github/workflows/pull-request.yml
+++ b/.github/workflows/pull-request.yml
@@ -5,43 +5,50 @@ on:
     branches: [ 'main' ]
 
 jobs:
-  tests:
-    runs-on: ubuntu-latest
-
-    services:
-      mariadb:
-        image: mariadb:latest
-        ports:
-          - 3306
-        env:
-          MYSQL_USER: dijon
-          MYSQL_PASSWORD: dijon
-          MYSQL_DATABASE: dijon
-          MYSQL_ROOT_PASSWORD: dijon
-        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3
-
+#  tests:
+#    runs-on: ubuntu-latest
+#    services:
+#      mariadb:
+#        image: mariadb:latest
+#        ports:
+#          - 3306
+#        env:
+#          MYSQL_USER: dijon
+#          MYSQL_PASSWORD: dijon
+#          MYSQL_DATABASE: dijon
+#          MYSQL_ROOT_PASSWORD: dijon
+#        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3
+#
+#    steps:
+#      - uses: actions/checkout@v1
+#
+#      - name: Verify MariaDB connection
+#        env:
+#          DBPORT: ${{ job.services.mariadb.ports[3306] }}
+#        run: |
+#          while ! mysqladmin ping -h"127.0.0.1" -P"$DBPORT" --silent; do
+#            sleep 1
+#          done
+#
+#      - name: Set up Python 3.9
+#        uses: actions/setup-python@v1
+#        with:
+#          python-version: 3.9
+#      - name: Install dependencies
+#        run: |
+#          python -m pip install --upgrade pip
+#          pip install poetry
+#          poetry install
+#      - name: Run Tests
+#        env:
+#          DYNACONF_DBPORT: ${{ job.services.mariadb.ports[3306] }}
+#        run: |
+#          make test
+  build:
+    container:
+      image: 'ubuntu:20.04'
+    name: Build image
     steps:
-      - uses: actions/checkout@v1
-
-      - name: Verify MariaDB connection
-        env:
-          DBPORT: ${{ job.services.mariadb.ports[3306] }}
+      - name: Build image
         run: |
-          while ! mysqladmin ping -h"127.0.0.1" -P"$DBPORT" --silent; do
-            sleep 1
-          done
-
-      - name: Set up Python 3.9
-        uses: actions/setup-python@v1
-        with:
-          python-version: 3.9
-      - name: Install dependencies
-        run: |
-          python -m pip install --upgrade pip
-          pip install poetry
-          poetry install
-      - name: Run Tests
-        env:
-          DBPORT: ${{ job.services.mariadb.ports[3306] }}
-        run: |
-          make test
+          echo hello
