caching

diff --git a/.github/workflows/pull-request.yml b/.github/workflows/pull-request.yml
--- a/.github/workflows/pull-request.yml
+++ b/.github/workflows/pull-request.yml
@@ -1,26 +1,78 @@
-name: Conditional
+name: 'pull-request'
 
 on:
   pull_request:
     branches: [ 'main' ]
 
 jobs:
-  job1:
+  tests:
     runs-on: ubuntu-latest
-    steps:
-      - name: Fail
-        run: |
-          exit 1
-  run-if-failed:
-    runs-on: ubuntu-latest
-    needs: [job1]
-#    if: always() && (needs.job1.result == 'failure' || needs.job2.result == 'failure')
-    steps:
-      - name: Needs context
+    services:
+      mariadb:
+        image: mariadb:latest
+        ports:
+          - 3306
         env:
-          NEEDS_CONTEXT: ${{ toJSON(needs) }}
+          MYSQL_USER: dijon
+          MYSQL_PASSWORD: dijon
+          MYSQL_DATABASE: dijon
+          MYSQL_ROOT_PASSWORD: dijon
+        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3
+    steps:
+      - uses: actions/checkout@v1
+
+      - name: Set up Python 3.9
+        uses: actions/setup-python@v1
+        with:
+          python-version: 3.9
+
+      - name: Install Poetry
+        uses: snok/install-poetry@v1.1.7
+
+      - name: Load cached $HOME/.local
+        uses: actions/cache@v2.1.6
+        with:
+          path: ~/.local
+          key: dotlocal-${{ runner.os }}-${{ hashFiles('.github/workflows/pull-request.yml') }}
+
+
+      - name: Load cached venv
+        id: cached-poetry-dependencies
+        uses: actions/cache@v2.1.6
+        with:
+          path: deployer/.venv
+          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}-${{ hashFiles('.github/workflows/pull-request.yml') }}
+
+
+      - name: Install dependencies
         run: |
-          echo "$NEEDS_CONTEXT"
+          poetry install
+        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
+
+      - name: Run Tests
+        env:
+          DYNACONF_DBPORT: ${{ job.services.mariadb.ports[3306] }}
+        run: |
+          make test
+
+
+#jobs:
+#  job1:
+#    runs-on: ubuntu-latest
+#    steps:
+#      - name: Fail
+#        run: |
+#          exit 1
+#  run-if-failed:
+#    runs-on: ubuntu-latest
+#    needs: [job1]
+##    if: always() && (needs.job1.result == 'failure' || needs.job2.result == 'failure')
+#    steps:
+#      - name: Needs context
+#        env:
+#          NEEDS_CONTEXT: ${{ toJSON(needs) }}
+#        run: |
+#          echo "$NEEDS_CONTEXT"
 
 
 
